### PR TITLE
Add missing RGBA properties

### LINKED ISSUE #9: TextTag missing property
If I am not mistaken Gtk.TextTag is missing some properties:
- https://developer.gnome.org/gtk3/stable/GtkTextTag.html#GtkTextTag--background-rgba
- https://developer.gnome.org/gtk3/stable/GtkTextTag.html#GtkTextTag--foreground-rgba

### PR DESCRIPTION
**Pull request by harry-cpp**
Fixes #9

### CODE REVIEW

**Comment by mikkeljohnsen** [comment]
I have just made a push that uses GdkRGBA in Gtk. Could you please test if it works ?

I see in this pull request you use "val.Val" and the generated code I have just pushed don't. So please get back to me if it doesn't work.

**Comment by harry-cpp** [comment]
Yes, your commit fixed this.

**Comment by harry-cpp** [comment]
Just gonna mention that https://developer.gnome.org/gtk3/stable/GtkTextTag.html#GtkTextTag--background-gdk also seems to not be generated, tho that property is depricated.

**Comment by mikkeljohnsen** [comment]
Yes, I know. But since it is deprecated I didn't want to spend time on it.

**Comment by mikkeljohnsen** [comment]
Just pushed so "background-gdk" is generated. Not sure if it works.

**Comment by mikkeljohnsen** [comment]
Could you test the latest push ?

**Comment by harry-cpp** [comment]
I can't right now, will test as soon as I can.

**Comment by harry-cpp** [comment]
Working.

**Pull request closed without merging**
